module Straddle
  class Client < Straddle::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    ENVIRONMENTS: {
      sandbox: "https://sandbox.straddle.com",
      production: "https://production.straddle.com"
    }

    attr_reader api_key: String

    attr_reader embed: Straddle::Resources::Embed

    attr_reader bridge: Straddle::Resources::Bridge

    attr_reader customers: Straddle::Resources::Customers

    attr_reader paykeys: Straddle::Resources::Paykeys

    attr_reader charges: Straddle::Resources::Charges

    attr_reader funding_events: Straddle::Resources::FundingEvents

    attr_reader payments: Straddle::Resources::Payments

    attr_reader payouts: Straddle::Resources::Payouts

    attr_reader reports: Straddle::Resources::Reports

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?environment: :sandbox | :production | nil,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
