configured_endpoints: 64
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/straddle/straddle-b55e80fe0bab3bafab12491dca2341844d66aecbbc3cfc1a1bd485df4ef52a5d.yml
openapi_spec_hash: 1aec85cf8eb0dba0f12055993f4c720c
config_hash: c3edc408d77a6a857b6f7575d35f219f
