configured_endpoints: 60
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/straddle%2Fstraddle-e3e0cdb548acdac46023fdb249287dccaaf06da3d5ae55850e2078fe30b1c19d.yml
openapi_spec_hash: 605eff1ada70607dea69e2fdfe14cc8a
config_hash: 0ce1f3aaa9b0f456132e23bbe8224fcb
