module Straddle
  module Models
    module Embed
      type account_update_params =
        {
          business_profile: Straddle::Embed::BusinessProfileV1,
          external_id: String?,
          metadata: ::Hash[Symbol, String?]?,
          correlation_id: String,
          request_id: String
        }
        & Straddle::Internal::Type::request_parameters

      class AccountUpdateParams < Straddle::Internal::Type::BaseModel
        extend Straddle::Internal::Type::RequestParameters::Converter
        include Straddle::Internal::Type::RequestParameters

        attr_accessor business_profile: Straddle::Embed::BusinessProfileV1

        attr_accessor external_id: String?

        attr_accessor metadata: ::Hash[Symbol, String?]?

        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (
          business_profile: Straddle::Embed::BusinessProfileV1,
          ?external_id: String?,
          ?metadata: ::Hash[Symbol, String?]?,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> void

        def to_hash: -> {
          business_profile: Straddle::Embed::BusinessProfileV1,
          external_id: String?,
          metadata: ::Hash[Symbol, String?]?,
          correlation_id: String,
          request_id: String,
          request_options: Straddle::RequestOptions
        }
      end
    end
  end
end
