module Straddle
  module Models
    module Embed
      type organization_get_params =
        { organization_id: String, correlation_id: String, request_id: String }
        & Straddle::Internal::Type::request_parameters

      class OrganizationGetParams < Straddle::Internal::Type::BaseModel
        extend Straddle::Internal::Type::RequestParameters::Converter
        include Straddle::Internal::Type::RequestParameters

        attr_accessor organization_id: String

        attr_reader correlation_id: String?

        def correlation_id=: (String) -> String

        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (
          organization_id: String,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> void

        def to_hash: -> {
          organization_id: String,
          correlation_id: String,
          request_id: String,
          request_options: Straddle::RequestOptions
        }
      end
    end
  end
end
