module Straddle
  module Models
    type bridge_token_v1 =
      {
        data: Straddle::BridgeTokenV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::BridgeTokenV1::response_type
      }

    class BridgeTokenV1 < Straddle::Internal::Type::BaseModel
      attr_accessor data: Straddle::BridgeTokenV1::Data

      attr_accessor meta: Straddle::ResponseMetadata

      attr_accessor response_type: Straddle::Models::BridgeTokenV1::response_type

      def initialize: (
        data: Straddle::BridgeTokenV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::BridgeTokenV1::response_type
      ) -> void

      def to_hash: -> {
        data: Straddle::BridgeTokenV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::BridgeTokenV1::response_type
      }

      type data = { bridge_token: String }

      class Data < Straddle::Internal::Type::BaseModel
        attr_accessor bridge_token: String

        def initialize: (bridge_token: String) -> void

        def to_hash: -> { bridge_token: String }
      end

      type response_type =
        :object | :array | :error | :none | :Object | :Array | :Error | :None

      module ResponseType
        extend Straddle::Internal::Type::Enum

        OBJECT: :object
        OBJECT_2: :Object
        ARRAY: :array
        ARRAY_2: :Array
        ERROR: :error
        ERROR_2: :Error
        NONE: :none
        NONE_2: :None

        def self?.values: -> ::Array[Straddle::Models::BridgeTokenV1::response_type]
      end
    end
  end
end
