module Straddle
  module Models
    type funding_event_list_params =
      {
        created_from: Date?,
        created_to: Date?,
        direction: Straddle::Models::FundingEventListParams::direction,
        event_type: Straddle::Models::FundingEventListParams::event_type,
        page_number: Integer,
        page_size: Integer,
        search_text: String?,
        sort_by: Straddle::Models::FundingEventListParams::sort_by,
        sort_order: Straddle::Models::FundingEventListParams::sort_order,
        status: ::Array[Straddle::Models::FundingEventListParams::status]?,
        status_reason: ::Array[Straddle::Models::FundingEventListParams::status_reason]?,
        status_source: ::Array[Straddle::Models::FundingEventListParams::status_source]?,
        trace_id: String?,
        trace_number: String?,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String
      }
      & Straddle::Internal::Type::request_parameters

    class FundingEventListParams < Straddle::Internal::Type::BaseModel
      extend Straddle::Internal::Type::RequestParameters::Converter
      include Straddle::Internal::Type::RequestParameters

      attr_accessor created_from: Date?

      attr_accessor created_to: Date?

      attr_reader direction: Straddle::Models::FundingEventListParams::direction?

      def direction=: (
        Straddle::Models::FundingEventListParams::direction
      ) -> Straddle::Models::FundingEventListParams::direction

      attr_reader event_type: Straddle::Models::FundingEventListParams::event_type?

      def event_type=: (
        Straddle::Models::FundingEventListParams::event_type
      ) -> Straddle::Models::FundingEventListParams::event_type

      attr_reader page_number: Integer?

      def page_number=: (Integer) -> Integer

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_accessor search_text: String?

      attr_reader sort_by: Straddle::Models::FundingEventListParams::sort_by?

      def sort_by=: (
        Straddle::Models::FundingEventListParams::sort_by
      ) -> Straddle::Models::FundingEventListParams::sort_by

      attr_reader sort_order: Straddle::Models::FundingEventListParams::sort_order?

      def sort_order=: (
        Straddle::Models::FundingEventListParams::sort_order
      ) -> Straddle::Models::FundingEventListParams::sort_order

      attr_accessor status: ::Array[Straddle::Models::FundingEventListParams::status]?

      attr_accessor status_reason: ::Array[Straddle::Models::FundingEventListParams::status_reason]?

      attr_accessor status_source: ::Array[Straddle::Models::FundingEventListParams::status_source]?

      attr_accessor trace_id: String?

      attr_accessor trace_number: String?

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader request_id: String?

      def request_id=: (String) -> String

      attr_reader straddle_account_id: String?

      def straddle_account_id=: (String) -> String

      def initialize: (
        ?created_from: Date?,
        ?created_to: Date?,
        ?direction: Straddle::Models::FundingEventListParams::direction,
        ?event_type: Straddle::Models::FundingEventListParams::event_type,
        ?page_number: Integer,
        ?page_size: Integer,
        ?search_text: String?,
        ?sort_by: Straddle::Models::FundingEventListParams::sort_by,
        ?sort_order: Straddle::Models::FundingEventListParams::sort_order,
        ?status: ::Array[Straddle::Models::FundingEventListParams::status]?,
        ?status_reason: ::Array[Straddle::Models::FundingEventListParams::status_reason]?,
        ?status_source: ::Array[Straddle::Models::FundingEventListParams::status_source]?,
        ?trace_id: String?,
        ?trace_number: String?,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> void

      def to_hash: -> {
        created_from: Date?,
        created_to: Date?,
        direction: Straddle::Models::FundingEventListParams::direction,
        event_type: Straddle::Models::FundingEventListParams::event_type,
        page_number: Integer,
        page_size: Integer,
        search_text: String?,
        sort_by: Straddle::Models::FundingEventListParams::sort_by,
        sort_order: Straddle::Models::FundingEventListParams::sort_order,
        status: ::Array[Straddle::Models::FundingEventListParams::status]?,
        status_reason: ::Array[Straddle::Models::FundingEventListParams::status_reason]?,
        status_source: ::Array[Straddle::Models::FundingEventListParams::status_source]?,
        trace_id: String?,
        trace_number: String?,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String,
        request_options: Straddle::RequestOptions
      }

      type direction = :deposit | :withdrawal

      module Direction
        extend Straddle::Internal::Type::Enum

        DEPOSIT: :deposit
        WITHDRAWAL: :withdrawal

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::direction]
      end

      type event_type =
        :charge_deposit | :charge_reversal | :payout_return | :payout_withdrawal

      module EventType
        extend Straddle::Internal::Type::Enum

        CHARGE_DEPOSIT: :charge_deposit
        CHARGE_REVERSAL: :charge_reversal
        PAYOUT_RETURN: :payout_return
        PAYOUT_WITHDRAWAL: :payout_withdrawal

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::event_type]
      end

      type sort_by = :transfer_date | :id | :amount

      module SortBy
        extend Straddle::Internal::Type::Enum

        TRANSFER_DATE: :transfer_date
        ID: :id
        AMOUNT: :amount

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::sort_by]
      end

      type sort_order = :asc | :desc

      module SortOrder
        extend Straddle::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::sort_order]
      end

      type status =
        :created
        | :scheduled
        | :failed
        | :cancelled
        | :on_hold
        | :pending
        | :paid
        | :reversed

      module Status
        extend Straddle::Internal::Type::Enum

        CREATED: :created
        SCHEDULED: :scheduled
        FAILED: :failed
        CANCELLED: :cancelled
        ON_HOLD: :on_hold
        PENDING: :pending
        PAID: :paid
        REVERSED: :reversed

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::status]
      end

      type status_reason =
        :insufficient_funds
        | :closed_bank_account
        | :invalid_bank_account
        | :invalid_routing
        | :disputed
        | :payment_stopped
        | :owner_deceased
        | :frozen_bank_account
        | :risk_review
        | :fraudulent
        | :duplicate_entry
        | :invalid_paykey
        | :payment_blocked
        | :amount_too_large
        | :too_many_attempts
        | :internal_system_error
        | :user_request
        | :ok
        | :other_network_return
        | :payout_refused
        | :cancel_request
        | :failed_verification
        | :require_review
        | :blocked_by_system
        | :watchtower_review

      module StatusReason
        extend Straddle::Internal::Type::Enum

        INSUFFICIENT_FUNDS: :insufficient_funds
        CLOSED_BANK_ACCOUNT: :closed_bank_account
        INVALID_BANK_ACCOUNT: :invalid_bank_account
        INVALID_ROUTING: :invalid_routing
        DISPUTED: :disputed
        PAYMENT_STOPPED: :payment_stopped
        OWNER_DECEASED: :owner_deceased
        FROZEN_BANK_ACCOUNT: :frozen_bank_account
        RISK_REVIEW: :risk_review
        FRAUDULENT: :fraudulent
        DUPLICATE_ENTRY: :duplicate_entry
        INVALID_PAYKEY: :invalid_paykey
        PAYMENT_BLOCKED: :payment_blocked
        AMOUNT_TOO_LARGE: :amount_too_large
        TOO_MANY_ATTEMPTS: :too_many_attempts
        INTERNAL_SYSTEM_ERROR: :internal_system_error
        USER_REQUEST: :user_request
        OK: :ok
        OTHER_NETWORK_RETURN: :other_network_return
        PAYOUT_REFUSED: :payout_refused
        CANCEL_REQUEST: :cancel_request
        FAILED_VERIFICATION: :failed_verification
        REQUIRE_REVIEW: :require_review
        BLOCKED_BY_SYSTEM: :blocked_by_system
        WATCHTOWER_REVIEW: :watchtower_review

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::status_reason]
      end

      type status_source =
        :watchtower | :bank_decline | :customer_dispute | :user_action | :system

      module StatusSource
        extend Straddle::Internal::Type::Enum

        WATCHTOWER: :watchtower
        BANK_DECLINE: :bank_decline
        CUSTOMER_DISPUTE: :customer_dispute
        USER_ACTION: :user_action
        SYSTEM: :system

        def self?.values: -> ::Array[Straddle::Models::FundingEventListParams::status_source]
      end
    end
  end
end
