module Straddle
  module Models
    type paykey_v1 =
      {
        data: Straddle::PaykeyV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::PaykeyV1::response_type
      }

    class PaykeyV1 < Straddle::Internal::Type::BaseModel
      attr_accessor data: Straddle::PaykeyV1::Data

      attr_accessor meta: Straddle::ResponseMetadata

      attr_accessor response_type: Straddle::Models::PaykeyV1::response_type

      def initialize: (
        data: Straddle::PaykeyV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::PaykeyV1::response_type
      ) -> void

      def to_hash: -> {
        data: Straddle::PaykeyV1::Data,
        meta: Straddle::ResponseMetadata,
        response_type: Straddle::Models::PaykeyV1::response_type
      }

      type data =
        {
          id: String,
          config: Straddle::PaykeyV1::Data::Config,
          created_at: Time,
          label: String,
          paykey: String,
          source: Straddle::Models::PaykeyV1::Data::source,
          status: Straddle::Models::PaykeyV1::Data::status,
          updated_at: Time,
          balance: Straddle::PaykeyV1::Data::Balance,
          bank_data: Straddle::PaykeyV1::Data::BankData,
          customer_id: String?,
          expires_at: Time?,
          external_id: String?,
          institution_name: String?,
          metadata: ::Hash[Symbol, String]?,
          status_details: Straddle::PaykeyV1::Data::StatusDetails,
          unblock_eligible: bool?
        }

      class Data < Straddle::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor config: Straddle::PaykeyV1::Data::Config

        attr_accessor created_at: Time

        attr_accessor label: String

        attr_accessor paykey: String

        attr_accessor source: Straddle::Models::PaykeyV1::Data::source

        attr_accessor status: Straddle::Models::PaykeyV1::Data::status

        attr_accessor updated_at: Time

        attr_reader balance: Straddle::PaykeyV1::Data::Balance?

        def balance=: (
          Straddle::PaykeyV1::Data::Balance
        ) -> Straddle::PaykeyV1::Data::Balance

        attr_reader bank_data: Straddle::PaykeyV1::Data::BankData?

        def bank_data=: (
          Straddle::PaykeyV1::Data::BankData
        ) -> Straddle::PaykeyV1::Data::BankData

        attr_accessor customer_id: String?

        attr_accessor expires_at: Time?

        attr_accessor external_id: String?

        attr_accessor institution_name: String?

        attr_accessor metadata: ::Hash[Symbol, String]?

        attr_reader status_details: Straddle::PaykeyV1::Data::StatusDetails?

        def status_details=: (
          Straddle::PaykeyV1::Data::StatusDetails
        ) -> Straddle::PaykeyV1::Data::StatusDetails

        attr_accessor unblock_eligible: bool?

        def initialize: (
          id: String,
          config: Straddle::PaykeyV1::Data::Config,
          created_at: Time,
          label: String,
          paykey: String,
          source: Straddle::Models::PaykeyV1::Data::source,
          status: Straddle::Models::PaykeyV1::Data::status,
          updated_at: Time,
          ?balance: Straddle::PaykeyV1::Data::Balance,
          ?bank_data: Straddle::PaykeyV1::Data::BankData,
          ?customer_id: String?,
          ?expires_at: Time?,
          ?external_id: String?,
          ?institution_name: String?,
          ?metadata: ::Hash[Symbol, String]?,
          ?status_details: Straddle::PaykeyV1::Data::StatusDetails,
          ?unblock_eligible: bool?
        ) -> void

        def to_hash: -> {
          id: String,
          config: Straddle::PaykeyV1::Data::Config,
          created_at: Time,
          label: String,
          paykey: String,
          source: Straddle::Models::PaykeyV1::Data::source,
          status: Straddle::Models::PaykeyV1::Data::status,
          updated_at: Time,
          balance: Straddle::PaykeyV1::Data::Balance,
          bank_data: Straddle::PaykeyV1::Data::BankData,
          customer_id: String?,
          expires_at: Time?,
          external_id: String?,
          institution_name: String?,
          metadata: ::Hash[Symbol, String]?,
          status_details: Straddle::PaykeyV1::Data::StatusDetails,
          unblock_eligible: bool?
        }

        type config =
          {
            processing_method: Straddle::Models::PaykeyV1::Data::Config::processing_method,
            sandbox_outcome: Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome
          }

        class Config < Straddle::Internal::Type::BaseModel
          attr_reader processing_method: Straddle::Models::PaykeyV1::Data::Config::processing_method?

          def processing_method=: (
            Straddle::Models::PaykeyV1::Data::Config::processing_method
          ) -> Straddle::Models::PaykeyV1::Data::Config::processing_method

          attr_reader sandbox_outcome: Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome?

          def sandbox_outcome=: (
            Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome
          ) -> Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome

          def initialize: (
            ?processing_method: Straddle::Models::PaykeyV1::Data::Config::processing_method,
            ?sandbox_outcome: Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome
          ) -> void

          def to_hash: -> {
            processing_method: Straddle::Models::PaykeyV1::Data::Config::processing_method,
            sandbox_outcome: Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome
          }

          type processing_method = :inline | :background | :skip

          module ProcessingMethod
            extend Straddle::Internal::Type::Enum

            INLINE: :inline
            BACKGROUND: :background
            SKIP: :skip

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::Config::processing_method]
          end

          type sandbox_outcome = :standard | :active | :rejected | :review

          module SandboxOutcome
            extend Straddle::Internal::Type::Enum

            STANDARD: :standard
            ACTIVE: :active
            REJECTED: :rejected
            REVIEW: :review

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::Config::sandbox_outcome]
          end
        end

        type source = :bank_account | :straddle | :mx | :plaid | :tan | :quiltt

        module Source
          extend Straddle::Internal::Type::Enum

          BANK_ACCOUNT: :bank_account
          STRADDLE: :straddle
          MX: :mx
          PLAID: :plaid
          TAN: :tan
          QUILTT: :quiltt

          def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::source]
        end

        type status =
          :pending | :active | :inactive | :rejected | :review | :blocked

        module Status
          extend Straddle::Internal::Type::Enum

          PENDING: :pending
          ACTIVE: :active
          INACTIVE: :inactive
          REJECTED: :rejected
          REVIEW: :review
          BLOCKED: :blocked

          def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::status]
        end

        type balance =
          {
            status: Straddle::Models::PaykeyV1::Data::Balance::status,
            account_balance: Integer?,
            updated_at: Time?
          }

        class Balance < Straddle::Internal::Type::BaseModel
          attr_accessor status: Straddle::Models::PaykeyV1::Data::Balance::status

          attr_accessor account_balance: Integer?

          attr_accessor updated_at: Time?

          def initialize: (
            status: Straddle::Models::PaykeyV1::Data::Balance::status,
            ?account_balance: Integer?,
            ?updated_at: Time?
          ) -> void

          def to_hash: -> {
            status: Straddle::Models::PaykeyV1::Data::Balance::status,
            account_balance: Integer?,
            updated_at: Time?
          }

          type status = :pending | :completed | :failed

          module Status
            extend Straddle::Internal::Type::Enum

            PENDING: :pending
            COMPLETED: :completed
            FAILED: :failed

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::Balance::status]
          end
        end

        type bank_data =
          {
            account_number: String,
            account_type: Straddle::Models::PaykeyV1::Data::BankData::account_type,
            routing_number: String
          }

        class BankData < Straddle::Internal::Type::BaseModel
          attr_accessor account_number: String

          attr_accessor account_type: Straddle::Models::PaykeyV1::Data::BankData::account_type

          attr_accessor routing_number: String

          def initialize: (
            account_number: String,
            account_type: Straddle::Models::PaykeyV1::Data::BankData::account_type,
            routing_number: String
          ) -> void

          def to_hash: -> {
            account_number: String,
            account_type: Straddle::Models::PaykeyV1::Data::BankData::account_type,
            routing_number: String
          }

          type account_type = :checking | :savings

          module AccountType
            extend Straddle::Internal::Type::Enum

            CHECKING: :checking
            SAVINGS: :savings

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::BankData::account_type]
          end
        end

        type status_details =
          {
            changed_at: Time,
            message: String,
            reason: Straddle::Models::PaykeyV1::Data::StatusDetails::reason,
            source: Straddle::Models::PaykeyV1::Data::StatusDetails::source,
            code: String?
          }

        class StatusDetails < Straddle::Internal::Type::BaseModel
          attr_accessor changed_at: Time

          attr_accessor message: String

          attr_accessor reason: Straddle::Models::PaykeyV1::Data::StatusDetails::reason

          attr_accessor source: Straddle::Models::PaykeyV1::Data::StatusDetails::source

          attr_accessor code: String?

          def initialize: (
            changed_at: Time,
            message: String,
            reason: Straddle::Models::PaykeyV1::Data::StatusDetails::reason,
            source: Straddle::Models::PaykeyV1::Data::StatusDetails::source,
            ?code: String?
          ) -> void

          def to_hash: -> {
            changed_at: Time,
            message: String,
            reason: Straddle::Models::PaykeyV1::Data::StatusDetails::reason,
            source: Straddle::Models::PaykeyV1::Data::StatusDetails::source,
            code: String?
          }

          type reason =
            :insufficient_funds
            | :closed_bank_account
            | :invalid_bank_account
            | :invalid_routing
            | :disputed
            | :payment_stopped
            | :owner_deceased
            | :frozen_bank_account
            | :risk_review
            | :fraudulent
            | :duplicate_entry
            | :invalid_paykey
            | :payment_blocked
            | :amount_too_large
            | :too_many_attempts
            | :internal_system_error
            | :user_request
            | :ok
            | :other_network_return
            | :payout_refused
            | :cancel_request
            | :failed_verification
            | :require_review
            | :blocked_by_system
            | :watchtower_review
            | :InsufficientFunds
            | :ClosedBankAccount
            | :InvalidBankAccount
            | :InvalidRouting
            | :Disputed
            | :PaymentStopped
            | :OwnerDeceased
            | :FrozenBankAccount
            | :RiskReview
            | :Fraudulent
            | :DuplicateEntry
            | :InvalidPaykey
            | :PaymentBlocked
            | :AmountTooLarge
            | :TooManyAttempts
            | :InternalSystemError
            | :UserRequest
            | :Ok
            | :OtherNetworkReturn
            | :PayoutRefused

          module Reason
            extend Straddle::Internal::Type::Enum

            INSUFFICIENT_FUNDS: :insufficient_funds
            INSUFFICIENT_FUNDS_2: :InsufficientFunds
            CLOSED_BANK_ACCOUNT: :closed_bank_account
            CLOSED_BANK_ACCOUNT_2: :ClosedBankAccount
            INVALID_BANK_ACCOUNT: :invalid_bank_account
            INVALID_BANK_ACCOUNT_2: :InvalidBankAccount
            INVALID_ROUTING: :invalid_routing
            INVALID_ROUTING_2: :InvalidRouting
            DISPUTED: :disputed
            DISPUTED_2: :Disputed
            PAYMENT_STOPPED: :payment_stopped
            PAYMENT_STOPPED_2: :PaymentStopped
            OWNER_DECEASED: :owner_deceased
            OWNER_DECEASED_2: :OwnerDeceased
            FROZEN_BANK_ACCOUNT: :frozen_bank_account
            FROZEN_BANK_ACCOUNT_2: :FrozenBankAccount
            RISK_REVIEW: :risk_review
            RISK_REVIEW_2: :RiskReview
            FRAUDULENT: :fraudulent
            FRAUDULENT_2: :Fraudulent
            DUPLICATE_ENTRY: :duplicate_entry
            DUPLICATE_ENTRY_2: :DuplicateEntry
            INVALID_PAYKEY: :invalid_paykey
            INVALID_PAYKEY_2: :InvalidPaykey
            PAYMENT_BLOCKED: :payment_blocked
            PAYMENT_BLOCKED_2: :PaymentBlocked
            AMOUNT_TOO_LARGE: :amount_too_large
            AMOUNT_TOO_LARGE_2: :AmountTooLarge
            TOO_MANY_ATTEMPTS: :too_many_attempts
            TOO_MANY_ATTEMPTS_2: :TooManyAttempts
            INTERNAL_SYSTEM_ERROR: :internal_system_error
            INTERNAL_SYSTEM_ERROR_2: :InternalSystemError
            USER_REQUEST: :user_request
            USER_REQUEST_2: :UserRequest
            OK: :ok
            OK_2: :Ok
            OTHER_NETWORK_RETURN: :other_network_return
            OTHER_NETWORK_RETURN_2: :OtherNetworkReturn
            PAYOUT_REFUSED: :payout_refused
            PAYOUT_REFUSED_2: :PayoutRefused
            CANCEL_REQUEST: :cancel_request
            FAILED_VERIFICATION: :failed_verification
            REQUIRE_REVIEW: :require_review
            BLOCKED_BY_SYSTEM: :blocked_by_system
            WATCHTOWER_REVIEW: :watchtower_review

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::StatusDetails::reason]
          end

          type source =
            :watchtower
            | :bank_decline
            | :customer_dispute
            | :user_action
            | :system
            | :Watchtower
            | :BankDecline
            | :CustomerDispute
            | :UserAction
            | :System

          module Source
            extend Straddle::Internal::Type::Enum

            WATCHTOWER: :watchtower
            WATCHTOWER_2: :Watchtower
            BANK_DECLINE: :bank_decline
            BANK_DECLINE_2: :BankDecline
            CUSTOMER_DISPUTE: :customer_dispute
            CUSTOMER_DISPUTE_2: :CustomerDispute
            USER_ACTION: :user_action
            USER_ACTION_2: :UserAction
            SYSTEM: :system
            SYSTEM_2: :System

            def self?.values: -> ::Array[Straddle::Models::PaykeyV1::Data::StatusDetails::source]
          end
        end
      end

      type response_type =
        :object | :array | :error | :none | :Object | :Array | :Error | :None

      module ResponseType
        extend Straddle::Internal::Type::Enum

        OBJECT: :object
        OBJECT_2: :Object
        ARRAY: :array
        ARRAY_2: :Array
        ERROR: :error
        ERROR_2: :Error
        NONE: :none
        NONE_2: :None

        def self?.values: -> ::Array[Straddle::Models::PaykeyV1::response_type]
      end
    end
  end
end
