module Straddle
  module Models
    type payout_update_params =
      {
        amount: Integer,
        description: String,
        payment_date: Date,
        metadata: ::Hash[Symbol, String]?,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String
      }
      & Straddle::Internal::Type::request_parameters

    class PayoutUpdateParams < Straddle::Internal::Type::BaseModel
      extend Straddle::Internal::Type::RequestParameters::Converter
      include Straddle::Internal::Type::RequestParameters

      attr_accessor amount: Integer

      attr_accessor description: String

      attr_accessor payment_date: Date

      attr_accessor metadata: ::Hash[Symbol, String]?

      attr_reader correlation_id: String?

      def correlation_id=: (String) -> String

      attr_reader request_id: String?

      def request_id=: (String) -> String

      attr_reader straddle_account_id: String?

      def straddle_account_id=: (String) -> String

      def initialize: (
        amount: Integer,
        description: String,
        payment_date: Date,
        ?metadata: ::Hash[Symbol, String]?,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> void

      def to_hash: -> {
        amount: Integer,
        description: String,
        payment_date: Date,
        metadata: ::Hash[Symbol, String]?,
        correlation_id: String,
        request_id: String,
        straddle_account_id: String,
        request_options: Straddle::RequestOptions
      }
    end
  end
end
