module Straddle
  module Resources
    class Embed
      class Accounts
        attr_reader capability_requests: Straddle::Resources::Embed::Accounts::CapabilityRequests

        def create: (
          access_level: Straddle::Models::Embed::AccountCreateParams::access_level,
          account_type: Straddle::Models::Embed::AccountCreateParams::account_type,
          business_profile: Straddle::Embed::BusinessProfileV1,
          organization_id: String,
          ?external_id: String?,
          ?metadata: ::Hash[Symbol, String?]?,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Embed::AccountV1

        def update: (
          String account_id,
          business_profile: Straddle::Embed::BusinessProfileV1,
          ?external_id: String?,
          ?metadata: ::Hash[Symbol, String?]?,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Embed::AccountV1

        def list: (
          ?page_number: Integer,
          ?page_size: Integer,
          ?search_text: String,
          ?sort_by: String,
          ?sort_order: Straddle::Models::Embed::AccountListParams::sort_order,
          ?status: Straddle::Models::Embed::AccountListParams::status,
          ?type: Straddle::Models::Embed::AccountListParams::type_,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Internal::PageNumberSchema[Straddle::Embed::AccountPagedV1::Data]

        def get: (
          String account_id,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Embed::AccountV1

        def onboard: (
          String account_id,
          terms_of_service: Straddle::Embed::TermsOfServiceV1,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Embed::AccountV1

        def simulate: (
          String account_id,
          ?final_status: Straddle::Models::Embed::AccountSimulateParams::final_status,
          ?correlation_id: String,
          ?request_id: String,
          ?request_options: Straddle::request_opts
        ) -> Straddle::Embed::AccountV1

        def initialize: (client: Straddle::Client) -> void
      end
    end
  end
end
