module Straddle
  module Resources
    class Paykeys
      def list: (
        ?customer_id: String,
        ?page_number: Integer,
        ?page_size: Integer,
        ?sort_by: Straddle::Models::PaykeyListParams::sort_by,
        ?sort_order: Straddle::Models::PaykeyListParams::sort_order,
        ?source: ::Array[Straddle::Models::PaykeyListParams::source],
        ?status: ::Array[Straddle::Models::PaykeyListParams::status],
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::Internal::PageNumberSchema[Straddle::PaykeySummaryPagedV1::Data]

      def cancel: (
        String id,
        ?reason: String?,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::PaykeyV1

      def get: (
        String id,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::PaykeyV1

      def reveal: (
        String id,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::Models::PaykeyRevealResponse

      def review: (
        String id,
        status: Straddle::Models::PaykeyReviewParams::status,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::PaykeyV1

      def unmasked: (
        String id,
        ?correlation_id: String,
        ?request_id: String,
        ?straddle_account_id: String,
        ?request_options: Straddle::request_opts
      ) -> Straddle::PaykeyUnmaskedV1

      def initialize: (client: Straddle::Client) -> void
    end
  end
end
