# frozen_string_literal: true

module Straddle
  module Models
    module Bridge
      # @see Straddle::Resources::Bridge::Link#plaid
      class LinkPlaidParams < Straddle::Internal::Type::BaseModel
        extend Straddle::Internal::Type::RequestParameters::Converter
        include Straddle::Internal::Type::RequestParameters

        # @!attribute customer_id
        #   Unique identifier of the related customer object.
        #
        #   @return [String]
        required :customer_id, String

        # @!attribute plaid_token
        #   Plaid processor token generated by your application for use with the Straddle
        #   API.
        #
        #   @return [String]
        required :plaid_token, String

        # @!attribute config
        #
        #   @return [Straddle::Models::Bridge::LinkPlaidParams::Config, nil]
        optional :config, -> { Straddle::Bridge::LinkPlaidParams::Config }

        # @!attribute metadata
        #   Up to 20 additional user-defined key-value pairs. Useful for storing additional
        #   information about the paykey in a structured format.
        #
        #   @return [Hash{Symbol=>String}, nil]
        optional :metadata, Straddle::Internal::Type::HashOf[String], nil?: true

        # @!attribute correlation_id
        #
        #   @return [String, nil]
        optional :correlation_id, String

        # @!attribute request_id
        #
        #   @return [String, nil]
        optional :request_id, String

        # @!attribute straddle_account_id
        #
        #   @return [String, nil]
        optional :straddle_account_id, String

        # @!method initialize(customer_id:, plaid_token:, config: nil, metadata: nil, correlation_id: nil, request_id: nil, straddle_account_id: nil, request_options: {})
        #   Some parameter documentations has been truncated, see
        #   {Straddle::Models::Bridge::LinkPlaidParams} for more details.
        #
        #   @param customer_id [String] Unique identifier of the related customer object.
        #
        #   @param plaid_token [String] Plaid processor token generated by your application for use with the Straddle AP
        #
        #   @param config [Straddle::Models::Bridge::LinkPlaidParams::Config]
        #
        #   @param metadata [Hash{Symbol=>String}, nil] Up to 20 additional user-defined key-value pairs. Useful for storing additional
        #
        #   @param correlation_id [String]
        #
        #   @param request_id [String]
        #
        #   @param straddle_account_id [String]
        #
        #   @param request_options [Straddle::RequestOptions, Hash{Symbol=>Object}]

        class Config < Straddle::Internal::Type::BaseModel
          # @!attribute sandbox_outcome
          #
          #   @return [Symbol, Straddle::Models::Bridge::LinkPlaidParams::Config::SandboxOutcome, nil]
          optional :sandbox_outcome, enum: -> { Straddle::Bridge::LinkPlaidParams::Config::SandboxOutcome }

          # @!method initialize(sandbox_outcome: nil)
          #   @param sandbox_outcome [Symbol, Straddle::Models::Bridge::LinkPlaidParams::Config::SandboxOutcome]

          # @see Straddle::Models::Bridge::LinkPlaidParams::Config#sandbox_outcome
          module SandboxOutcome
            extend Straddle::Internal::Type::Enum

            STANDARD = :standard
            ACTIVE = :active
            REJECTED = :rejected

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end
  end
end
